name: With yq script

env:
  NEW_TAG: ${{ github.sha }}

on:
  push

jobs:
  Change-image-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: list elements
        run : ls -lah

      - name: Checkout second repo
        uses: actions/checkout@v3
        with:
          repository: 'tereza-arta/manifest-for-yq'

      - name: list elements in second repo
        run : ls -lah    

      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers.[0].image = $NEW_TAG dir/deploy.yaml'
