name: With yq script

on:
  push

jobs:
  Change-image-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: list elements
        run : ls -lah

      - name: Checkout second repo
        uses: actions/checkout@v3
        with:
          repository: 'https://github.com/tereza-arta/manifest-for-yq.git'

      - name: list elements in second repo
        run : ls -lah    
