name: With yq script

#env:
  #NEW_TAG: ${{ github.sha }}

on:
  workflow_run:
    workflows: ["Workflow first"]
    types:
      completed

jobs:
  docker:
    uses: tereza-arta/reusable/.github/workflows/workflow.yaml@main
    with:
      path: dir
      filename: deploy.yaml
