name: With yq script

env:
  NEW_TAG: ${{ github.sha }}

on:
  push

jobs:
  Change-image-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: list elements
        run : ls -lah

      - name: Clone target repo
        run : |
          git clone https://github.com/tereza-arta/manifest-for-yq.git
          cd manifest-for-yq
          
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.31.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq   

      - name: Update YAML file with yq
        working-directory: manifest-for-yq
        run: |
          yq e '.spec.template.spec.containers.[0].image = $NEW_TAG' -i dir/deploy.yaml

      - name: Commit and Push Changes
        working-directory: manifest-for-yq
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git add dir/deploy.yaml
          git commit -m "Update image in k8s deployment"
          git push origin main
